# Generated by Django 2.2.9 on 2020-01-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='columns',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='num_columns',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
