# Generated by Django 2.2.9 on 2020-06-07 08:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations


def make_empty_json_columns(apps, schema_editor):
    Device = apps.get_model('devices', 'Device')

    Device.objects.update(columns='[]')


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20200119_2015'),
    ]

    operations = [
        migrations.RunPython(
            make_empty_json_columns,
        ),
        migrations.AlterField(
            model_name='device',
            name='columns',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
