# Generated by Django 2.2.9 on 2020-07-29 16:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devices', '0004_remove_device_num_columns'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('user', 'sequence_id')},
        ),
    ]
