# Generated by Django 3.2.16 on 2022-10-11 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0001_initial'),
        ('measurements', '0003_alter_measurement_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurement_set', to='runs.run'),
        ),
    ]
